import 'dotenv/config';
import { connect, disconnect } from './src/db.js';
import Employee from './src/models/Employee.js';
import Department from './src/models/Department.js';
import OtEntry from './src/models/OtEntry.js';
const c = await connect();
const adm = await Department.findOne({ code: 'ADM' }).lean();
console.log('ADM:', adm.nameTh, '· otMode =', adm.otMode, '· manager field =', adm.manager);
const people = await Employee.find({ department: adm._id }).select('code name role position company active').lean();
console.log('\nคนใน ADM:');
for (const p of people) console.log(` ${p.code.padEnd(9)} ${p.name.padEnd(22)} ${p.role.padEnd(9)} ${p.position || ''} ${p.active===false?'(ปิด)':''}`);
console.log('\nหัวหน้าทั้งหมดบนทะเบียน (ผู้ที่ tick ADM เพิ่มได้):');
const mgrs = await Employee.find({ role: 'manager' }).populate('department','code').select('code name department company approvesCompany approvesDepartments active').lean();
for (const m of mgrs) console.log(` ${m.code.padEnd(9)} ${m.name.padEnd(22)} สังกัด ${m.department?.code?.padEnd(5)} คุมเพิ่ม=${(m.approvesDepartments||[]).length} ${m.active===false?'(ปิด)':''}`);
console.log('\nใบ OT ของ ADM ที่เคยมี:', await OtEntry.countDocuments({ department: adm._id }));
await disconnect();
